# Generated by Django 2.2.1 on 2020-02-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_loginuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='phone',
            field=models.ImageField(default='img/gtl.jpg', upload_to='img', verbose_name='图片'),
        ),
    ]
