# Generated by Django 2.2.1 on 2020-02-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0008_auto_20200227_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_description',
            field=models.TextField(default='goods', verbose_name='商品描述'),
        ),
    ]
